force-app/main/default/objects/Contact/fields/AssociatedWealth_XDossier__c.field-meta.xml
<CustomField>
    <fullName>AssociatedWealth_XDossier__c</fullName>
    <label>Associated Wealth-X Dossier</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WXIntegration__Wealth_X_Dossier_Id__c.field-meta.xml
<CustomField>
    <fullName>WXIntegration__Wealth_X_Dossier_Id__c</fullName>
    <label>Wealth-X Dossier Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WealthXTest.cls
@isTest
private class WealthXTest {

    static testMethod void WealthXTest(){
        Contact contactObj = new Contact (
			AssociatedWealth_XDossier__c = 'https://test.com/apex/Wealth_X_SearchedDossier?dossier=2056&',
            LastName = 'Test'
			
		);
		insert contactObj;
        system.debug(contactObj.Id);
        WealthX.displayUrlID(new List<Id>{contactObj.Id});
		Contact c = [ select Id, WXIntegration__Wealth_X_Dossier_Id__c from Contact where Id=:contactObj.Id];
        System.assertEquals(2056, c.WXIntegration__Wealth_X_Dossier_Id__c);
    }
    
}